### ISSUE TITLE
Cannot connect to database after initial injection

### ISSUE THREAD

**Issue by ybizeul** [pierrecdn/phpipam#36]
Regarding issue : https://github.com/phpipam/phpipam/issues/2290

Unless specified otherwise, phpipam injects a standard user/password for later database access once the initial injection is done.

This results in impossibility to connect as the default host for the connection is `localhost`, which prevents phpipam container to connect to the database.

**Comment by pierrecdn** [comment]
Hi,
Maybe I didn't understand your issue, so feel free to correct me.

First, localhost is changed to `mysql` by default, so that people can freely link their containers using `--link my-specific-name:mysql`
Someone also introduced the ability to [customize the mysql host](https://github.com/pierrecdn/phpipam/commit/01236cec35470cfe5ab34e56eadd93401f176566).

So in the container setup, accesses are always seen as "remote".

Does it anwser your concerns?

**Comment by ybizeul** [comment]
I should have done a better job documenting this... I can't remember now what went wrong now. I guess we can close this.

Thanks for answering, I'll comment next time I install it.

**Comment by ybizeul** [comment]
Just talked to a friend, he had the same issue, he reminded me : The problem was on the DB side, things were fine on the php config files, but privileges in the DB (injected my the initial setup of the DB by php) specifies credentials `user@localhost` in the `GRANT` statement. After that, MySQL rejects connections from the phpipam container, you have to manually GRANT `user@%`

**Comment by pierrecdn** [comment]
If you follow the README instructions you shouldn't have these grant issues.
I guess the DB setup was somehow specific?

**Comment by pierrecdn** [comment]
Is it still the case if you pull `latest`? I just commited https://github.com/pierrecdn/phpipam/commit/cb4ec5baf6e9022f50d7027bc52f55f8788d631e, it should fix common installations.
Feel free to reopen if still broken.

**Comment by ybizeul** [comment]
Thanks Pierre, I'll check and report here if needed!
